### ISSUE TITLE
Suggestion: README.md

### ISSUE THREAD

**Issue by MihaiBojin** [gdemacedo/sub-tracker#1]
A `README.md` file which explains what the project is about, how it can be set-up, etc. would be great!

This can encourage other developers to contribute to this project.

Here's a [good guide](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2); there are others out there!

Cheers,
M

**Comment by gmcestari** [comment]
Cool, makes sense
It was on my list of things to add, just added an initial version there - will do for now!
Thanks!
